# Generated by Django 4.0.1 on 2022-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_name', models.CharField(max_length=100)),
                ('Food_Catagories', models.CharField(max_length=50)),
                ('Food_price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
